config/routes.rb
Rails.application.routes.draw do
  get 'help'    => 'welcome#help'
  get 'about'   => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'users'    => 'users#new'
  resources :relatorios
  resources :produtos
  resources :funcionarios
  resources :users

  root 'welcome#home'
end

app/models/relatorio.rb
class Relatorio < ActiveRecord::Base
      belongs_to :produtos
      validates :content, length: { maximum: 140 }

end

app/controllers/relatorios_controller.rb
class RelatoriosController < ApplicationController
  before_action :set_relatorio, only: [:show, :edit, :update, :destroy]

  # GET /relatorios
  # GET /relatorios.json
  def index
    @relatorios = Relatorio.all
  end

  # GET /relatorios/1
  # GET /relatorios/1.json
  def show
  end

  # GET /relatorios/new
  def new
    @relatorio = Relatorio.new
  end

  # GET /relatorios/1/edit
  def edit
  end

  # POST /relatorios
  # POST /relatorios.json
  def create
    @relatorio = Relatorio.new(relatorio_params)

    respond_to do |format|
      if @relatorio.save
        format.html { redirect_to @relatorio, notice: 'Relatorio criado com sucesso.' }
        format.json { render :show, status: :created, location: @relatorio }
      else
        format.html { render :new }
        format.json { render json: @relatorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /relatorios/1
  # PATCH/PUT /relatorios/1.json
  def update
    respond_to do |format|
      if @relatorio.update(relatorio_params)
        format.html { redirect_to @relatorio, notice: 'Relatorio atualizado com sucesso. ' }
        format.json { render :show, status: :ok, location: @relatorio }
      else
        format.html { render :edit }
        format.json { render json: @relatorio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /relatorios/1
  # DELETE /relatorios/1.json
  def destroy
    @relatorio.destroy
    respond_to do |format|
      format.html { redirect_to relatorios_url, notice: 'Relatorio removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_relatorio
      @relatorio = Relatorio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def relatorio_params
      params.require(:relatorio).permit(:content, :produto_id)
    end
end

app/helpers/relatorios_helper.rb
module RelatoriosHelper
end

app/views/relatorios/_form.html.erb
<%= form_for(@relatorio) do |f| %>
  <% if @relatorio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@relatorio.errors.count, "error") %> prohibited this relatorio from being saved:</h2>

      <ul>
      <% @relatorio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content, "Quantidade" %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :produto_id %><br>
    <%= f.number_field :produto_id %>
  </div>
  <div class="actions">
    <%= f.submit 'Gerar Relatorio' %>
  </div>
<% end %>

app/views/relatorios/edit.html.erb
<h1>Editar Relatorio</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @relatorio %> |
<%= link_to 'Voltar', relatorios_path %>

app/views/relatorios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Relatorios</h1>

<table>
  <thead>
    <tr>
      <th>Quantidade</th>
      <th>Produto</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @relatorios.each do |relatorio| %>
      <tr>
        <td><%= relatorio.content %></td>
        <td><%= relatorio.produto_id %></td>
        <td><%= link_to 'Detalhes', relatorio %></td>
        <td><%= link_to 'Editar', edit_relatorio_path(relatorio) %></td>
        <td><%= link_to 'Remover', relatorio, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/relatorios/new.html.erb
<h1>Novo Relatorio</h1>
<div class="center jumbotron">
<%= render 'form' %>

<%= link_to 'Voltar', relatorios_path %>

app/views/relatorios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Quantidade:</strong>
  <%= @relatorio.content %>
</p>

<p>
  <strong>Produto:</strong>
  <%= @relatorio.produto_id %>
</p>

<%= link_to 'Editar', edit_relatorio_path(@relatorio) %> |
<%= link_to 'Voltar', relatorios_path %>