config/routes.rb
Rails.application.routes.draw do
  get 'help'    => 'welcome#help'
  get 'about'   => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'users'    => 'users#new'
  resources :relatorios
  resources :produtos
  resources :funcionarios
  resources :users

  root 'welcome#home'
end

app/models/produto.rb
class Produto < ActiveRecord::Base
    has_many :relatorios
end

app/controllers/produtos_controller.rb
class ProdutosController < ApplicationController
  before_action :set_produto, only: [:show, :edit, :update, :destroy]

  # GET /produtos
  def index
    @produtos = Produto.all
  end

  # GET /produtos/1
  def show
  end

  # GET /produtos/new
  def new
    @produto = Produto.new
  end

  # GET /produtos
  def edit
  end

  # POST /produtos
  def create
    @produto = Produto.new(produto_params)

    respond_to do |format|
      if @produto.save
        format.html { redirect_to @produto, notice: 'Produto criado com sucesso.' }
        format.json { render :show, status: :created, location: @produto }
      else
        format.html { render :new }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /produtos/1
  # PATCH/PUT /produtos/1.json
  def update
    respond_to do |format|
      if @produto.update(produto_params)
        format.html { redirect_to @produto, notice: 'Produto atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @produto }
      else
        format.html { render :edit }
        format.json { render json: @produto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /produtos/1
  # DELETE /produtos/1.json
  def destroy
    @produto.destroy
    respond_to do |format|
      format.html { redirect_to produtos_url, notice: 'Produto removido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_produto
      @produto = Produto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def produto_params
      params.require(:produto).permit(:name, :validade, :marca, :peso)
    end
end

app/helpers/produtos_helper.rb
module ProdutosHelper
end

app/views/produtos/_form.html.erb
<%= form_for(@produto) do |f| %>
  <% if @produto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@produto.errors.count, "error") %> prohibited this produto from being saved:</h2>

      <ul>
      <% @produto.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, "Nome" %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :validade %><br>
    <%= f.text_field :validade %>
  </div>
  <div class="field">
    <%= f.label :marca %><br>
    <%= f.text_field :marca %>
  </div>
  <div class="field">
    <%= f.label :peso %><br>
    <%= f.number_field :peso %>
  </div>
  <div class="actions">
    <%= f.submit 'Adicionar'%>
  </div>
<% end %>

app/views/produtos/edit.html.erb
<h1>Editar Produto</h1>

<%= render 'form' %>

<%= link_to 'Detalhes', @produto %> |
<%= link_to 'Voltar', produtos_path %>

app/views/produtos/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Lista de Produtos</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Validade</th>
      <th>Marca</th>
      <th>Peso</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @produtos.each do |produto| %>
      <tr>
        <td><%= produto.name %></td>
        <td><%= produto.validade %></td>
        <td><%= produto.marca %></td>
        <td><%= produto.peso %></td>
        <td><%= link_to 'Detalhes', produto %></td>
        <td><%= link_to 'Editar', edit_produto_path(produto) %></td>
        <td><%= link_to 'Remover', produto, method: :delete, data: { confirm: 'Tem certeza?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/produtos/new.html.erb
<h1>Novo Produto</h1>
<div class="center jumbotron">
<%= render 'form' %>

<%= link_to 'Voltar', produtos_path %>

app/views/produtos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @produto.name %>
</p>

<p>
  <strong>Validade:</strong>
  <%= @produto.validade %>
</p>

<p>
  <strong>Marca:</strong>
  <%= @produto.marca %>
</p>

<p>
  <strong>Peso:</strong>
  <%= @produto.peso %>
</p>

<%= link_to 'Editar', edit_produto_path(@produto) %> |
<%= link_to 'Voltar', produtos_path %>