config/routes.rb
Rails.application.routes.draw do
  get 'help'    => 'welcome#help'
  get 'about'   => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'signup'  => 'users#new'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'

  get 'users'    => 'users#new'
  resources :relatorios
  resources :produtos
  resources :funcionarios
  resources :users

  root 'welcome#home'
end

app/views/layouts/application.html.erb
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag 'application', media: 'all',
                                           'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->
  </head>
  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <%= link_to "Bem Vindo", '#', id: "logo" %>
        <nav>
          <ul class="nav navbar-nav pull-right">
          <li><%= link_to "Inicio",   root_path %></li>
          <% if current_user %>
          <li> <%= link_to "Adicione Funcionario", '/funcionarios/new' %> </li>
          <li> <%= link_to "Adicione Produto", '/produtos/new' %> </li>
          <li> <%= link_to "Adicione Relatorio", '/relatorios/new' %> </li>
          <li> <%= link_to "Lista de Funcionarios", '/funcionarios' %> </li>
          <li> <%= link_to "Lista de Produtos", '/produtos' %> </li>
          <li> <%= link_to "Lista de Relatorios", '/relatorios' %> </li>

          <% end %>
          <% if !logged_in? %>
            <li><%= link_to "Logar", '/login' %></li>
            <li><%= link_to "Sobre",   '/about' %></li>
          
            <% else %>
              <li><%= link_to "Deslogar", logout_path, method: "delete" %></li>
            <% end %>
    
          </ul>
        </nav>
      </div>
    </header>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>